// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkUEudYSh5iVrBJ6g1Kkotk6g8GgoW2bQ',
    appId: '1:64415760498:web:969f19a13eb41ce55142eb',
    messagingSenderId: '64415760498',
    projectId: 'internship-test-8c994',
    authDomain: 'internship-test-8c994.firebaseapp.com',
    databaseURL: 'https://internship-test-8c994-default-rtdb.firebaseio.com',
    storageBucket: 'internship-test-8c994.appspot.com',
    measurementId: 'G-643E0VTB9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkbhNokmDKsyI9shcUND6DIebQXNWQxyI',
    appId: '1:64415760498:android:63bfa6bec9fb56b95142eb',
    messagingSenderId: '64415760498',
    projectId: 'internship-test-8c994',
    databaseURL: 'https://internship-test-8c994-default-rtdb.firebaseio.com',
    storageBucket: 'internship-test-8c994.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUAzblZRwqRzcDy8G231F2MuZayzCVIuE',
    appId: '1:64415760498:ios:bd8d92328ff5dced5142eb',
    messagingSenderId: '64415760498',
    projectId: 'internship-test-8c994',
    databaseURL: 'https://internship-test-8c994-default-rtdb.firebaseio.com',
    storageBucket: 'internship-test-8c994.appspot.com',
    iosBundleId: 'com.example.internshipTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUAzblZRwqRzcDy8G231F2MuZayzCVIuE',
    appId: '1:64415760498:ios:bd8d92328ff5dced5142eb',
    messagingSenderId: '64415760498',
    projectId: 'internship-test-8c994',
    databaseURL: 'https://internship-test-8c994-default-rtdb.firebaseio.com',
    storageBucket: 'internship-test-8c994.appspot.com',
    iosBundleId: 'com.example.internshipTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkUEudYSh5iVrBJ6g1Kkotk6g8GgoW2bQ',
    appId: '1:64415760498:web:7832769ceb6e43ce5142eb',
    messagingSenderId: '64415760498',
    projectId: 'internship-test-8c994',
    authDomain: 'internship-test-8c994.firebaseapp.com',
    databaseURL: 'https://internship-test-8c994-default-rtdb.firebaseio.com',
    storageBucket: 'internship-test-8c994.appspot.com',
    measurementId: 'G-YRQHXZXS51',
  );
}
